name: SpringBoot Check Style
on:
  push:
    branches:
      - pipebranch
  pull_request:
    branches:
      - pipebranch
jobs:
  checkstyle:
    name: Checkstyle Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -O checkstyle.jar

      - name: Run Checkstyle
        run: java -jar checkstyle.jar -c checkstyle.xml src/main/java
